# Generated by Django 3.0.6 on 2020-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funuser', '0002_auto_20200306_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funuser',
            name='is_address_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_birth_date_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_college_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_hobby_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_hometown_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_motto_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_occupation_outward',
            field=models.BooleanField(default=False, verbose_name='Is outward ?'),
        ),
    ]
