# Generated by Django 3.2.4 on 2021-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funuser', '0003_auto_20201003_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funuser',
            name='is_address_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_birth_date_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_college_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_hobby_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_hometown_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_motto_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
        migrations.AlterField(
            model_name='funuser',
            name='is_occupation_outward',
            field=models.BooleanField(default=False, verbose_name='公开 ?'),
        ),
    ]
