# Generated by Django 3.0.3 on 2020-02-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciation',
            name='invitee',
            field=models.CharField(default='', max_length=8, verbose_name='invitee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appreciation',
            name='invitee_title',
            field=models.CharField(default='', max_length=8, verbose_name='invitee title'),
            preserve_default=False,
        ),
    ]
