# Generated by Django 3.0.3 on 2020-03-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0002_auto_20200216_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funhomesticker',
            options={'verbose_name': 'Home sticker(NEW)', 'verbose_name_plural': 'Home stickers(NEW)'},
        ),
        migrations.AlterField(
            model_name='funhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden ?'),
        ),
        migrations.AlterField(
            model_name='homesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden ?'),
        ),
    ]
