# Generated by Django 3.0.3 on 2020-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0004_auto_20200304_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='home_comment',
            field=models.TextField(max_length=128, verbose_name='comment'),
        ),
    ]
