# Generated by Django 3.0.3 on 2020-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0005_auto_20200304_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funhomesticker',
            options={'verbose_name': '主页贴纸(NEW)', 'verbose_name_plural': '主页贴纸(NEW)'},
        ),
        migrations.AlterField(
            model_name='funhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
        migrations.AlterField(
            model_name='homesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
    ]
