# Generated by Django 3.0.3 on 2020-04-20 03:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0006_auto_20200306_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=4096, verbose_name='appreciation content'),
        ),
        migrations.AlterField(
            model_name='appreciation',
            name='home_comment',
            field=models.TextField(max_length=128, verbose_name='home comment'),
        ),
    ]
