# Generated by Django 3.0.6 on 2020-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0007_auto_20200420_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funhomesticker',
            options={'verbose_name': 'Home sticker(NEW)', 'verbose_name_plural': 'Home stickers(NEW)'},
        ),
        migrations.AlterModelOptions(
            name='homesticker',
            options={'verbose_name': 'Home sticker(deprecation)', 'verbose_name_plural': 'Home sticker(deprecation)'},
        ),
        migrations.AlterField(
            model_name='funhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden ?'),
        ),
        migrations.AlterField(
            model_name='homesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden ?'),
        ),
    ]
