# Generated by Django 3.2.4 on 2021-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funhome', '0008_auto_20201003_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funhomesticker',
            options={'verbose_name': '主页贴纸(NEW)', 'verbose_name_plural': '主页贴纸(NEW)'},
        ),
        migrations.AlterField(
            model_name='funhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
        migrations.AlterField(
            model_name='homesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
    ]
