# Generated by Django 3.2.7 on 2021-10-03 15:48

import uuid

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eduhub', '0003_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('_content', ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='Content')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduhub.classification', verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Appraising',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('point', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.CharField(max_length=64, verbose_name='Comment')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraising.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Appraising',
                'verbose_name_plural': 'Appraisings',
            },
        ),
    ]
