# Generated by Django 2.2.6 on 2019-11-09 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funfile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=64)),
                ('cover', models.ImageField(upload_to=funfile.models.upload_to)),
                ('creating_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
