# Generated by Django 2.2.6 on 2019-10-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='classification name', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Eduhub',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='title', max_length=64, unique=True)),
                ('document_file', models.FileField(help_text='document file', upload_to='eduhub_document_files')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='uploaded time')),
                ('author', models.ForeignKey(help_text='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classifications', models.ManyToManyField(help_text='classifications', to='eduhub.Classification')),
            ],
        ),
    ]
