# Generated by Django 2.2.6 on 2019-10-30 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='title', max_length=64, unique=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='uploaded time')),
                ('media_file', models.FileField(help_text='document file (.pdf, .mp4, .webm, .mkv only, pdf size less than 2 Mib, others size less than 0 Mib)', upload_to='eduhub_document_files', validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp4', 'webm', 'mkv'])])),
                ('author', models.ForeignKey(help_text='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
