# Generated by Django 3.0.3 on 2020-03-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduhubhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_legal',
            field=models.BooleanField(default=True, verbose_name='合法 ?'),
        ),
    ]
