# Generated by Django 2.2.6 on 2019-10-28 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eduhub',
            new_name='Article',
        ),
    ]
