# Generated by Django 3.0.3 on 2020-04-20 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eduhub', '0002_auto_20200306_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('test_title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Test commit')),
                ('test_text', models.TextField(max_length=12288, verbose_name='Template text')),
                ('submitting_date', models.DateTimeField(auto_now_add=True, verbose_name='Test submitting date')),
                ('last_modifying_date', models.DateTimeField(blank=True, null=True, verbose_name='Last modifying date')),
                ('test_commit', models.CharField(blank=True, max_length=64, null=True, verbose_name='Test commit')),
                ('test_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Test owner')),
            ],
            options={
                'verbose_name': 'Eduhub Test',
                'verbose_name_plural': 'Eduhub Tests',
            },
        ),
    ]
