# Generated by Django 3.0.6 on 2020-10-03 12:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0003_funtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduhubhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden ?'),
        ),
        migrations.AlterField(
            model_name='funcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2048, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_legal',
            field=models.BooleanField(default=True, verbose_name='Is label legal ?'),
        ),
    ]
