# Generated by Django 3.2.4 on 2021-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduhub', '0004_auto_20201003_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduhubhomesticker',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='隐藏(不贴) ?'),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_legal',
            field=models.BooleanField(default=True, verbose_name='合法 ?'),
        ),
    ]
