# Generated by Django 2.2.6 on 2019-10-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wearticle',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='title', max_length=64, unique=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, help_text='uploaded time')),
                ('author', models.ForeignKey(help_text='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='content', max_length=128)),
                ('like', models.IntegerField(default=0, help_text='like')),
                ('dislike', models.IntegerField(default=0, help_text='dislike')),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='time')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wearticle', models.ForeignKey(help_text='article', on_delete=django.db.models.deletion.CASCADE, to='wearticle.Wearticle')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
